name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm' # <-- PNPM
#          cache: 'npm'
#      - run: npm ci
      - run: pnpm i --frozen-lockfile # <-- PNPM
#      - run: npm run build --if-present
      - run: pnpm run build # <-- PNPM
      - name: Set ENV
        run: echo "PACKAGE_VERSION=$(npm pkg get version|sed 's/"//g')" >> $GITHUB_ENV
      - name: Test Version
        run: echo ${{env.PACKAGE_VERSION}}
      - name: Zip folder
        run: sudo apt install zip unzip
      - name: move to release folder
#        run: cd build # <-- NPM
        run: |        # <-- pnpm/vite
          cd dist 
          pwd
          ls
#      - name: Pack folder
#        run: zip -r Build_v${{env.PACKAGE_VERSION}}.zip .
#      - name: "Upload Artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: Build_v${{env.PACKAGE_VERSION}}
##          path: build
#          path: Build_v${{env.PACKAGE_VERSION}}.zip # <-- PNPM/VITE