name: Deploy in server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_CI_CD }}
#      - run: |
#          touch test.txt
      - run: |
          mkdir dist
          touch dist/test.txt
      - name: Upload files
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: "64.23.144.200"
          username: "developer"
          key: ${{ secrets.SSH_CI_CD }}
          uploads: |
            ./dist => ./latest_build/$DEST_FOLDER_NAME
