name: Deploy in server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: webfactory/ssh-agent@v0.8.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_CI_CD }}
#      - run: |
#          touch test.txt
      - run: |
          mkdir dist
          touch dist/test.txt
      - name: "SFTP deploy"
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: "developer"
          server: "64.23.144.200"
          ssh_private_key: ${{ secrets.SSH_CI_CD }}
          local_path: './dist/*'
          remote_path: '.'
          sftpArgs: '-o ConnectTimeout=5'