name: Deploy in server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: webfactory/ssh-agent@v0.8.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_CI_CD }}
#      - run: |
#          touch test.txt
      - run: |
          touch test.txt
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "64.23.144.200"
          remote-user: "developer"
          ssh-private-key: ${{ secrets.SSH_CI_CD }}
          remote-path: "."